version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:application --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    env_file:
      - .env

  faststream:
    build: .
    container_name: faststream_app
    command: python -m faststream run app.main.broker
    depends_on:
      - rabbitmq
      - db
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}  # Переменные окружения для RabbitMQ
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}  # Переменные окружения для PostgreSQL
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: