# Используем официальный базовый образ Python
FROM python:3.11-slim

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Устанавливаем Poetry
RUN pip install poetry

# Копируем файл pyproject.toml и poetry.lock
COPY pyproject.toml poetry.lock ./

# Устанавливаем зависимости без создания виртуального окружения
RUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi

# Копируем все файлы проекта в контейнер
COPY . .

# Открываем порт для приложения
EXPOSE 8000
