"""Added initial table

Revision ID: 8fe6f2938cfb
Revises: 
Create Date: 2024-08-11 18:20:04.518870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe6f2938cfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_metadata',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=250), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=250), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_file_metadata_original_name'), 'file_metadata', ['original_name'], unique=False)
    op.create_index(op.f('ix_file_metadata_uuid'), 'file_metadata', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_metadata_uuid'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_original_name'), table_name='file_metadata')
    op.drop_table('file_metadata')
    # ### end Alembic commands ###
